const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;

// In this exercise, you will need to work out what num represents?
//num represents a random number between minimum(1) and maximum(100), inclusive.

// Try breaking down the expression and using documentation to explain what it means
//Math.random() gives a random decimal number between 0 (inclusive) and 1 (exclusive).Example: 0.005, 0.15, 0.999 etc.
//Math.floor() removes the decimal part and rounds the number down to the nearest whole number. So the value becomes a whole number from 0 and 99.
//maximum - minimum + 1 gives the range of numbers we want to generate, which is 100 - 1 + 1 = 100. This means we want to generate a random number between 1 and 100, inclusive.
//Math.random() * (maximum - minimum + 1) gives a random decimal number between 0 (inclusive) and 100 (exclusive).Example: 0.15 * 100 = 15, 0.88 * 100 = 88, 0.999 * 100 = 99.9 etc.
//Math.floor(Math.random() * (maximum - minimum + 1)) gives a random whole number between 0 (inclusive) and 99 (exclusive). Adding the minimum value shifts this range to between 1 (inclusive) and 100 (inclusive).
//+ minimum shifts the range of random numbers generated by Math.floor(Math.random() * (maximum - minimum + 1)) from 0-99 to 1-100, inclusive. This makes the final result a whole number between 1 and 100, inclusive.

// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing
console.log(num);