const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;

// In this exercise, you will need to work out what num represents?
// Try breaking down the expression and using documentation to explain what it means
// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing


/*

In this exercise, num is a variable that stores the random whole number generated by the expression so it can be used later in the program.

1. Math.randon() picks a random decimal number  

2. maximum - minimum + 1; finds how many numbers are in the range

3. Math.floor() rounds the decimal down

4. +minimum adds the minimum value


*/