const minimum = 1;
const maximum = 100;

const num = Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;
console.log(num)
// In this exercise, you will need to work out what num represents?
// Try breaking down the expression and using documentation to explain what it means
// It will help to think about the order in which expressions are evaluated
// Try logging the value of num and running the program several times to build an idea of what the program is doing

// The variable num represents a integer number obtained as a result of a math operation including 
// the math functions floor and random, to obtain a random number between 1 and 100.
// Math.random(): generates an random decimal number. Math.floor(): rounds a number down to the nearest integer.

// The order of the expressions: 
// 1. The arithmetic operations  100 (maximum) - 1 (minimum) + 1
// 2. A random decimal number between 0 and 1 (no included) is generated by the random function and multiplied by 100
// 3. The number is rounded with the floor function
// 4. Is added the number + 1 to permit the possibility of to obtain 1 or 100
